#      
#  / - 

#    

  #      (  ,   )
   

  #   
  #   , , , 
   "크루즈여행"

  #   
  
    -  ""
       .  # %  
       "고급 여행객 타겟"

    -  ""
       .  # %  
       "가족 여행객 타겟"

    -  ""
       .  # %  
       "합리적 여행객 타겟"

    -  ""
       .  # %  
       "모험 추구 여행객 타겟"

#    

  #     
   

  #       
   

  #      
   

  #      ()
   

  #   () -  
   

  #  
  
       # 
       # 
     ""  #   ()
     
     ""

#    

  #    (  )
   ""

  #  -  (%     -)
   .

  #   
  
     .
     .
     .
     .
     .

  #  
  
    #    ()
     
     

    #  
     
     

    #  
     
     

#    

  #   ( )
  
     "-.-"
     .
     
    #   
     
     

  #  
  
     "----"
     .
     
    #  
     

  #   (   )
  
     ""  #  
     ""
     "--"  #   

  #  
  
     ""
     ""
     
     

#   

  #    (- )
   ""

  # 
   "/"

  #   
   

  #      (, )
  #     
   

#   &  

  #   
   

  #    ()
   

  #    ()
   


  #    (  )
   "$"

  #   
   
  
    - "."

  #  
  
     
     
       #    
       #     
     .  #       ($)
     .  #   -   

#    

  #  
   .  # 
   .  # 

  #     ()
  
     .  #  
     .
     .
     .

  #  
   
   

#   

  #     
   "//"

  #   
   "//"

  #  
   "//"

  #  
   "//"

  #  
  
    #     
     

    #    ()
     

    #   ()
     

  #   
   

#    

  #  
   

  #  
   

  #  
   
   

  # 
   
   
   

#   

  #   (, , , , )
   ""

  #  
   "%() %() %() %()"

  #  
  
     
     

  #   
  
     "."
     "."
     "."
     "."

#    

  #   
   

  #    (   )
   

  #    
   
   

  #    (    )
   

#    

  #  /    
   

  #     
   

  #   
   

  #    ( )
   

  #    
   

#   

  #      
   

  #      
   

  #   
   

  #  
   
   
